### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "13Peter@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "02345",
  "ort":"Musterstadt",
  "strasse": "Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Ja"
}

### Anlegen eines neuen Users
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Insekt",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "1.peter",
  "nachname": "Mustermann",
  "email": "1peter@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "2.peter",
  "email": "peter2mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "1peter@@hotmail.com",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "klein@outlook.de",
  "passwort": "8901GH",
  "postleitzahl": "069",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users mit falsches Mail Pattern @@
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "123456",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Hamburg 1",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am 1ten Peter",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "5peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "304b-404",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "80peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "51231234",
  "newsletter": "Nein"
}

###
GET /user HTTP/2
Host: localhost:8080

### Einloggen eines existierenden Users (Markus Heidmann)
POST /login HTTP/2
Host: localhost:8080
Content-Type: application/json

{"email": "ceo@playability.de", "password": "Adminpass"}

###
POST /logout HTTP/2
Host: localhost:8080
Content-Type: application/json

### Auslesen eines Users (Markus Heidmann)
GET /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{"email": "ceo@playability.de"}

### Bearbeiten eines Users (alle Daten)
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Mannfred",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "02345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Ja"
}

### Bearbeiten eines Users (nur Passwort)
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{

  "passwort": "neuesPasswort"
}

### Löschen eines Users
DELETE /deleteUser HTTP/2
Host: localhost:8080

### Auslesen eines nicht vorhanden Users
GET /user/error HTTP/2
Host: localhost:8080

HTTP/1.1 409 Conflict
Content-Type: text/plain

Diesen Nutzer gibt es nicht.

### Löschen eines nicht vorhanden Users
DELETE /user/error HTTP/2
Host: localhost


### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json
### Anlegen eines neuen Users (Jonas Thiele)
POST http://localhost:8080/user
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Jonas",
  "nachname": "Thiele",
  "email": "JonasTh@mni.thm.de",
  "passwort": "7890",
  "postleitzahl": 6273,
  "ort":"Wetzlar",
  "strasse": "Hauptstraße",
  "hnr": 26,
  "telefonnummer": "017683829974"
}

###

// User signing-in

POST http://localhost:8080/signin HTTP/2
Content-Type: application/json

{
  "email": "zacigg24@gmail.com",
  "passwort": "1234"
}
###


// User logging-out

POST http://localhost:8080/signout HTTP/2

###

###
GET http://localhost:8080/user
Content-Type: application/json
###




###

// User signing-in

POST http://localhost:8080/signin
Content-Type: application/json

{
  "email": "jannis.kempf@hotmail.de",
  "passwort": "123"
}
###


// User logging-out

POST http://localhost:8080/signout HTTP/2

###





###
GET /admin/user HTTP/2
Host: ip1-dbs.mni.thm.de

### Einloggen eines existierenden Users (Markus Heidmann)
POST /login HTTP/2
Host: localhost:8080
Content-Type: application/json

{"email": "ceo@playability.de", "password": "Adminpass"}

###
POST /logout HTTP/2
Host: localhost:8080
Content-Type: application/json

### Auslesen eines Users (Markus Heidmann)
GET /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{"email": "ceo@playability.de"}

### Bearbeiten eines Users (alle Daten)
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "vorname": "Muster",
  "nachname": "Maxmann",
  "passwort": "54321"
}

### Bearbeiten eines Users (nur Passwort)
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{

  "passwort": "neuesPasswort"
}

### Löschen eines Users
DELETE /deleteUser HTTP/2
Host: localhost:8080

### Auslesen eines nicht vorhanden Users
GET /user/error HTTP/2
Host: localhost:8080

HTTP/1.1 409 Conflict
Content-Type: text/plain

Diesen Nutzer gibt es nicht.

### Löschen eines nicht vorhanden Users
DELETE /user/error HTTP/2
Host: localhost


### Anlegen eines neuen Users (Max Mustermann)
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json



### GET all Products

GET /product
Host: localhost:8080
Content-Type: application/json

###
POST http://localhost:8080/signin
Content-Type: application/json

{
"email": "jannis.kempf@hotmail.de",
"passwort": "123"
}
###

###

### Produkt Warenkorb hinzufügen
GET /cart
Host: localhost:8080
Content-Type: application/json
###

### Produkt Warenkorb hinzufügen
PUT /cart
Host: localhost:8080
Content-Type: application/json

{"produktName": "Tactile Towers", "produktMenge":  1, "method":  "add"}
###



### Posten einer Lieferadresse
PUT /lieferadresse HTTP/2
Host: localhost:8080
Content-Type: application/json

{
"anrede": "Insekt",
"vorname": "Max",
"nachname": "Mustermann",
"postleitzahl": "12345",
"ort":"Musterstadt",
"strasse": "Am Musterweg",
"hnr": "1"
}


### Posten einer Rechnungsadresse
PUT /rechnungsadresse HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Insekt",
  "vorname": "Max",
  "nachname": "Mustermann",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1"
}