### ---------------- Richtige Angaben ------------------------
###

### Anlegen eines neuen Nutzers
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "13Peter@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "02345",
  "ort":"Musterstadt",
  "strasse": "Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Ja"
}

### Nutzer einsehen

GET /user HTTP/2
Host: localhost:8080


### Nutzer Einloggen
POST http://localhost:8080/signin
Content-Type: application/json

{
  "email": "jannis.kempf@hotmail.de",
  "passwort": "123"
}


### Nutzer Ausloggen

POST http://localhost:8080/signout HTTP/2


### Nutzer Bearbeiten

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Mannfred",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "02345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Ja"
}

### Löschen eines Users

DELETE /deleteUser HTTP/2
Host: localhost:8080


### Produkt Warenkorb hinzufügen mit methode: ADD

PUT /cart
Host: localhost:8080
Content-Type: application/json

{"produktName": "Shake n Match", "produktMenge":  2, "method":  "add"}

### Produkt Warenkorb hinzufügen mit methode: change

PUT /cart
Host: localhost:8080
Content-Type: application/json

{"produktName": "Shake n Match", "produktMenge":  4, "method":  "change"}

### Produkt Warenkorb hinzufügen
GET /cart
Host: localhost:8080
Content-Type: application/json


### Warenkorb Produkt Löschen (übergibt Name des Produkts)
DELETE /cart/Shake n Match
Host: localhost:8080
Content-Type: application/json





### ----------------Hier fehler Meldungen bei addUser--------------------

### falsches Anlegen eines neuen Users mit anrede "Insekt"
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Insekt",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches Anlegen eines neuen Users mit vorname "1.peter"
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "1.peter",
  "nachname": "Mustermann",
  "email": "1peter@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches Anlegen eines neuen Users mit nachname "2.peter"
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "2.peter",
  "email": "peter2mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches Anlegen eines neuen Users mit email "@@"
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "1peter@@hotmail.com",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches Anlegen eines neuen Users mit Postleitzahl muss 5 enthalten
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "klein@outlook.de",
  "passwort": "8901GH",
  "postleitzahl": "069",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users postleitzahl zu lang
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "123456",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users Ort falsch
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Hamburg 1",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users Strasse falsch
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am 1ten Peter",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Anlegen eines neuen Users Telefonnummer falsch
POST /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "80peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "51231234",
  "newsletter": "Nein"
}


### ----------------Hier fehler Meldungen bei editUser--------------------

### falsches ändern eines neuen Users mit anrede "Insekt"
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Insekt",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches ändern eines neuen Users mit vorname "1.peter"
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "1.peter",
  "nachname": "Mustermann",
  "email": "1peter@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches ändern eines neuen Users mit nachname "2.peter"
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "2.peter",
  "email": "peter2mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches ändern eines neuen Users mit email "@@"
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "1peter@@hotmail.com",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches ändern eines neuen Users mit passswort leer
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### falsches ändern eines Users mit Postleitzahl leer
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "klein@outlook.de",
  "postleitzahl": "",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Ändern eines neuen Users postleitzahl zu lang
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "123456",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Ändern eines neuen Users Ort falsch
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Hamburg 1",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Ändern eines Users Strasse falsch
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "2peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am 1ten Peter",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### Ändern eines Users Telefonnummer falsch
PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "80peter@outlook.de",
  "passwort": "15621526",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "51231234",
  "newsletter": "Nein"
}

### leere Angaben in Anrede

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### leere Angaben in Vorname

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### leere Angaben in Nachname

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### leere Angaben in Email

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### leere Angaben in passwort

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### leere Angaben in postleitzahl

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### leere Angaben in Ort

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### leere Angaben in Strasse

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}


### leere Angaben in Hausnummer

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "",
  "telefonnummer": "+1761956285",
  "newsletter": "Nein"
}

### leere Angaben in Telefonnummer

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "",
  "newsletter": "Nein"
}

### leere Angaben in Newsletter

PUT /user HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "anrede": "Herr",
  "vorname": "Max",
  "nachname": "Mustermann",
  "email": "max.mustermann@hotmail.de",
  "passwort": "12345",
  "postleitzahl": "12345",
  "ort":"Musterstadt",
  "strasse": "Am Musterweg",
  "hnr": "1",
  "telefonnummer": "+1761956285",
  "newsletter": ""
}

### falsches Produkt Warenkorb hinzufügen mit falschem Namen

PUT /cart
Host: localhost:8080
Content-Type: application/json

{"produktName": "", "produktMenge":  4, "method":  "change"}


### falsches Produkt Warenkorb hinzufügen mit falschem Namen

PUT /cart
Host: localhost:8080
Content-Type: application/json

{"produktName": "Kein Titel", "produktMenge":  4, "method":  "add"}


### falsches Produkt Warenkorb hinzufügen mit methode: ""

PUT /cart
Host: localhost:8080
Content-Type: application/json

{"produktName": "Tactile Towers", "produktMenge":  4, "method":  ""}